### ISSUE TITLE
binary files in resources/propbank

### ISSUE THREAD

**Issue by bheinzerling** [yoavartzi/amr#2]
After running getres.sh, there are binary files in the resources/propbank folders with names like "._bore.xml". On Linux, these will cause the PropBankReader to crash, since it attempts to parse all files in the directory.

The ._*.xml files appear to be OSX metadata. Maybe there's a difference in the way Files.walk(...) and/or Files.isRegularFile(...) treat them, e.g. ignore on OSX, while they're just normal files on Linux?

Anyway, a simple workaround is to do rm resources/propbank/._*.xml after running getres.sh

**Comment by yoavartzi** [comment]
Good catch. I fixed the getres.sh script to ignore the included resource
fork files. Now it should work out of the box.

Thanks!
