### ISSUE TITLE
AMR v.s SPF

### ISSUE THREAD

**Issue by matanox** [yoavartzi/amr#3]
Hi, 

Not really an issue, but how does this repo relate to https://github.com/cornell-lic/spf ?

Thanks!

**Comment by yoavartzi** [comment]
Great question. The AMR parser is based on SPF. It also includes code that is specific to AMR, including for learning and representation. It's quite challenging to keep the different projects in sync, so we separated them.

**Comment by matanox** [comment]
Thanks! I understand. I shall read through "Broad-coverage CCG Semantic Parsing with AMR" to get a better sense of it then. Thanks again.

**Comment by yoavartzi** [comment]
Happy to answer any questions that come up!
